### PR TITLE
Made videos autoplay

### PR DESCRIPTION
**Pull request by anwesh-b**
The videos now will autoplay and user should not manually click the play button

### CODE REVIEW

**Comment by coolbrg** [comment]
Hi @anwesh-b  , 

Are you working on it? There has been no update since our last interaction.

**Comment by anwesh-b** [comment]
Oh sorry, I will fix it asap

**Review by anwesh-b — COMMENTED** [review]
I have updated the autoplay option for next and prev button

**Review by coolbrg — APPROVED** [review]
Looks fine to me 👍 
Thanks, @anwesh-b for your contribution.

**Pull request merged**
